# Generated by Django 3.1.7 on 2021-03-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_project_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=1023)),
                ('text', models.CharField(max_length=8191)),
                ('is_blog', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogpost',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
